---
- name: Configure Docker to use insecure registry
  hosts: all
  become: true
  tasks:

    - name: Ensure Docker config directory exists
      file:
        path: /etc/docker
        state: directory
        mode: '0755'

    - name: Configure Docker daemon to allow insecure registry
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "insecure-registries": ["10.1.0.140:4000"]
          }
        mode: '0644'

    - name: Reload systemd to pick up docker changes
      command: systemctl daemon-reexec

    - name: Restart Docker
      systemd:
        name: docker
        state: restarted
        enabled: yes

